/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WheelSpinRouteImport } from './routes/wheel-spin'
import { Route as TreeScratchRouteImport } from './routes/tree-scratch'
import { Route as SiameseStickRouteImport } from './routes/siamese-stick'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as IncenseRouteImport } from './routes/incense'
import { Route as DreamRouteImport } from './routes/dream'
import { Route as BallDrawRouteImport } from './routes/ball-draw'
import { Route as IndexRouteImport } from './routes/index'

const WheelSpinRoute = WheelSpinRouteImport.update({
  id: '/wheel-spin',
  path: '/wheel-spin',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeScratchRoute = TreeScratchRouteImport.update({
  id: '/tree-scratch',
  path: '/tree-scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const SiameseStickRoute = SiameseStickRouteImport.update({
  id: '/siamese-stick',
  path: '/siamese-stick',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const IncenseRoute = IncenseRouteImport.update({
  id: '/incense',
  path: '/incense',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamRoute = DreamRouteImport.update({
  id: '/dream',
  path: '/dream',
  getParentRoute: () => rootRouteImport,
} as any)
const BallDrawRoute = BallDrawRouteImport.update({
  id: '/ball-draw',
  path: '/ball-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ball-draw': typeof BallDrawRoute
  '/dream': typeof DreamRoute
  '/incense': typeof IncenseRoute
  '/masters': typeof MastersRoute
  '/siamese-stick': typeof SiameseStickRoute
  '/tree-scratch': typeof TreeScratchRoute
  '/wheel-spin': typeof WheelSpinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ball-draw': typeof BallDrawRoute
  '/dream': typeof DreamRoute
  '/incense': typeof IncenseRoute
  '/masters': typeof MastersRoute
  '/siamese-stick': typeof SiameseStickRoute
  '/tree-scratch': typeof TreeScratchRoute
  '/wheel-spin': typeof WheelSpinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ball-draw': typeof BallDrawRoute
  '/dream': typeof DreamRoute
  '/incense': typeof IncenseRoute
  '/masters': typeof MastersRoute
  '/siamese-stick': typeof SiameseStickRoute
  '/tree-scratch': typeof TreeScratchRoute
  '/wheel-spin': typeof WheelSpinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ball-draw'
    | '/dream'
    | '/incense'
    | '/masters'
    | '/siamese-stick'
    | '/tree-scratch'
    | '/wheel-spin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ball-draw'
    | '/dream'
    | '/incense'
    | '/masters'
    | '/siamese-stick'
    | '/tree-scratch'
    | '/wheel-spin'
  id:
    | '__root__'
    | '/'
    | '/ball-draw'
    | '/dream'
    | '/incense'
    | '/masters'
    | '/siamese-stick'
    | '/tree-scratch'
    | '/wheel-spin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BallDrawRoute: typeof BallDrawRoute
  DreamRoute: typeof DreamRoute
  IncenseRoute: typeof IncenseRoute
  MastersRoute: typeof MastersRoute
  SiameseStickRoute: typeof SiameseStickRoute
  TreeScratchRoute: typeof TreeScratchRoute
  WheelSpinRoute: typeof WheelSpinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wheel-spin': {
      id: '/wheel-spin'
      path: '/wheel-spin'
      fullPath: '/wheel-spin'
      preLoaderRoute: typeof WheelSpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-scratch': {
      id: '/tree-scratch'
      path: '/tree-scratch'
      fullPath: '/tree-scratch'
      preLoaderRoute: typeof TreeScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siamese-stick': {
      id: '/siamese-stick'
      path: '/siamese-stick'
      fullPath: '/siamese-stick'
      preLoaderRoute: typeof SiameseStickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incense': {
      id: '/incense'
      path: '/incense'
      fullPath: '/incense'
      preLoaderRoute: typeof IncenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream': {
      id: '/dream'
      path: '/dream'
      fullPath: '/dream'
      preLoaderRoute: typeof DreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ball-draw': {
      id: '/ball-draw'
      path: '/ball-draw'
      fullPath: '/ball-draw'
      preLoaderRoute: typeof BallDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BallDrawRoute: BallDrawRoute,
  DreamRoute: DreamRoute,
  IncenseRoute: IncenseRoute,
  MastersRoute: MastersRoute,
  SiameseStickRoute: SiameseStickRoute,
  TreeScratchRoute: TreeScratchRoute,
  WheelSpinRoute: WheelSpinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
